TC01
logigear-thinhho/selenium-thinh pull request #1
Opened 2021-05-04 07:20 UTC by logigear-thinhho

2021-05-04 08:09 UTC, thanhlelgg requested changes

2021-05-04 08:09 UTC, thanhlelgg commented on src/main/java/page_objects/LoginPage.java
> +    private final By btnLogin = By.cssSelector("input[type='submit']");
this is a very weak xpath, new button implemented and this will fail

2021-05-04 08:09 UTC, thanhlelgg commented on src/main/java/page_objects/LoginPage.java
> +    private final By lblWelcomeMessage = By.cssSelector(".account strong");
don't use text formatting attribute while locating element

2021-05-04 08:09 UTC, thanhlelgg commented on src/test/java/tests/BaseTest.java
> +        System.out.println("Pre-condition");
use logger

2021-05-04 08:09 UTC, thanhlelgg commented on src/test/resources/testNG.xml
> +</suite>
add new line at EOF

2021-05-04 09:01 UTC, logigear-thinhho commented
Thank you for your review. I have fixed and pushed again into this branch. Please review my updated code.

2021-05-05 05:34 UTC, LoliSlayerMC approved these changes
LGTM

2021-05-05 06:08 UTC, merged